/*
 * Created on 20 nov. 2017 ( Time 23:22:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package ma.jberrich.dao;

import java.util.List;

import ma.jberrich.bean.Dept;

/**
 * Dept DAO interface
 * 
 * @author Telosys Tools
 */
public interface DeptDAO {

	/**
	 * findAll added by JBERRICH
	 * @return
	 */
	public List<Dept> findAll();
	
	public Dept findByName(String name);
	
	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param deptno
	 * @return the bean found or null if not found 
	 */
	public Dept find( int deptno ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param dept
	 * @return true if found, false if not found
	 */
	public boolean load( Dept dept ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param dept
	 */
	public void insert(Dept dept) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param dept
	 * @return
	 */
	public int update(Dept dept) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param deptno
	 * @return
	 */
	public int delete( int deptno ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param dept
	 * @return
	 */
	public int delete( Dept dept ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param deptno
	 * @return
	 */
	public boolean exists( int deptno ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param dept
	 * @return
	 */
	public boolean exists( Dept dept ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
