/*
 * Created on 20 nov. 2017 ( Time 23:22:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package ma.jberrich.dao;

import java.util.List;

import ma.jberrich.bean.Emp;

/**
 * Emp DAO interface
 * 
 * @author Telosys Tools
 */
public interface EmpDAO {

	/**
	 * findAll added by JBERRICH
	 * @return
	 */
	public List<Emp> findAll();
	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param empno
	 * @return the bean found or null if not found 
	 */
	public Emp find( int empno ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param emp
	 * @return true if found, false if not found
	 */
	public boolean load( Emp emp ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param emp
	 * @return the generated value for the auto-incremented column
	 */
	public int insert(Emp emp) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param emp
	 * @return
	 */
	public int update(Emp emp) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param empno
	 * @return
	 */
	public int delete( int empno ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param emp
	 * @return
	 */
	public int delete( Emp emp ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param empno
	 * @return
	 */
	public boolean exists( int empno ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param emp
	 * @return
	 */
	public boolean exists( Emp emp ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
