/*
 * Created on 20 nov. 2017 ( Time 23:22:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package ma.jberrich.dao.commons;

import java.sql.Connection;
import java.sql.SQLException;

import javax.sql.DataSource;

import ma.jberrich.dao.impl.jdbc.commons.DataSourceProvider;
import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit tests for DataSourceProvider
 * 
 * @author Telosys Tools
 *
 */
public class DataSourceProviderTest {

	@Test
	public void test1() throws SQLException {
    	System.out.println("test DataSourceProvider ");
    	
    	DataSource dataSource = DataSourceProvider.getDataSource();
    	System.out.println("DataSource ready. ");
    	
    	Connection c = dataSource.getConnection();
    	System.out.println("Connection ready. ");
    	
    	Assert.assertNotNull( c );
    	
    	c.close();
    	System.out.println("Connection closed. ");
	}
}
