/*
 * Created on 20 nov. 2017 ( Time 23:22:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package ma.jberrich.bean;

import java.io.Serializable;


/**
 * Java bean for 'Dept' entity
 * 
 * @author Telosys Tools
 *
 */
public class Dept implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : DEPTNO INT 
    private int deptno;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : DNAME VARCHAR 
    private String dname;

    // DB : LOC VARCHAR 
    private String loc;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setDeptno( int deptno ) {
        this.deptno = deptno ;
    }

    public int getDeptno() {
        return this.deptno;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDname( String dname ) {
        this.dname = dname;
    }
    public String getDname() {
        return this.dname;
    }

    public void setLoc( String loc ) {
        this.loc = loc;
    }
    public String getLoc() {
        return this.loc;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(deptno);
        sb.append("|");
        sb.append(dname);
        sb.append("|");
        sb.append(loc);
        return sb.toString(); 
    } 


}
