/*
 * Created on 20 nov. 2017 ( Time 23:22:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package ma.jberrich.bean;

import java.io.Serializable;


/**
 * Java bean for 'Emp' entity
 * 
 * @author Telosys Tools
 *
 */
public class Emp implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : EMPNO INT 
    private int empno;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : ENAME VARCHAR 
    private String ename;

    // DB : JOB VARCHAR 
    private String job;

    // DB : AGE INT 
    private int age;

    // DB : SAL DECIMAL 
    private int sal;

    // DB : DEPTNO INT 
    private int deptno;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setEmpno( int empno ) {
        this.empno = empno ;
    }

    public int getEmpno() {
        return this.empno;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setEname( String ename ) {
        this.ename = ename;
    }
    public String getEname() {
        return this.ename;
    }

    public void setJob( String job ) {
        this.job = job;
    }
    public String getJob() {
        return this.job;
    }

    public void setAge( int age ) {
        this.age = age;
    }
    public int getAge() {
        return this.age;
    }

    public void setSal( int sal ) {
        this.sal = sal;
    }
    public int getSal() {
        return this.sal;
    }

    public void setDeptno( int deptno ) {
        this.deptno = deptno;
    }
    public int getDeptno() {
        return this.deptno;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(empno);
        sb.append("|");
        sb.append(ename);
        sb.append("|");
        sb.append(job);
        sb.append("|");
        sb.append(age);
        sb.append("|");
        sb.append(sal);
        sb.append("|");
        sb.append(deptno);
        return sb.toString(); 
    } 


}
